name: adapter_autodock_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - rdkit
  - gemmi
  - meeko
  - cctbx-base
  - pymol-open-source
  - prody
  - pip
  - pip:
      - flask
      - python-dotenv
      - google-cloud-storage
      - git+https://github.com/forlilab/Meeko.git
      - git+https://github.com/ToolProof/helpers_py.git
